import {
    LayoutDashboard,
    Activity,
    BarChart3,
    Settings2,
    Zap,
    Clock,
    Trash2,
    Plus,
    Minus,
    X,
    User,
    Info,
    Brain,
    Sparkles,
    Filter,
    Flame,
    FileText,
    Check,
    CheckCircle,
    CircleAlert,
    BarChart2,
    TrendingUp,
    Moon,
    Sun,
    Download,
    Palette,
    Layout,
    Database,
    Code,
    LogOut,
    Lock,
    Pencil,
    ShieldCheck,
    LineChart,
    FileSpreadsheet,
    CloudCog,
    Bell,
    Star,
    Shield,
    StickyNote,
    Pin,
    Square,
    Play,
    RotateCcw,
    CheckSquare,
    Camera,
    Image as ImageIcon,
    UserX,
    UserCheck,
    Mail,
    Search,
    Send,
    Eraser,
    ChevronDown,
    ChevronUp
} from 'lucide-react';

const Icon = ({ name, size = 18, className = "" }) => {
    const icons = {
        'layout-dashboard': LayoutDashboard,
        'activity': Activity,
        'bar-chart-3': BarChart3,
        'settings-2': Settings2,
        'zap': Zap,
        'clock': Clock,
        'trash': Trash2,
        'plus': Plus,
        'minus': Minus,
        'x': X,
        'user': User,
        'info': Info,
        'brain': Brain,
        'sparkles': Sparkles,
        'filter': Filter,
        'flame': Flame,
        'file-text': FileText,
        'check': Check,
        'check-circle': CheckCircle,
        'alert-circle': CircleAlert,
        'bar-chart-2': BarChart2,
        'trending-up': TrendingUp,
        'moon': Moon,
        'sun': Sun,
        'download': Download,
        'palette': Palette,
        'layout': Layout,
        'database': Database,
        'code': Code,
        'log-out': LogOut,
        'lock': Lock,
        'pencil': Pencil,
        'shield-check': ShieldCheck,
        'line-chart': LineChart,
        'file-spreadsheet': FileSpreadsheet,
        'cloud-sync': CloudCog,
        'bell': Bell,
        'star': Star,
        'shield': Shield,
        'sticky-note': StickyNote,
        'pin': Pin,
        'square': Square,
        'play': Play,
        'rotate-ccw': RotateCcw,
        'check-square': CheckSquare,
        'camera': Camera,
        'image': ImageIcon,
        'user-x': UserX,
        'user-check': UserCheck,
        'mail': Mail,
        'search': Search,
        'send': Send,
        'edit': Pencil,
        'eraser': Eraser,
        'chevron-down': ChevronDown,
        'chevron-up': ChevronUp
    };

    const LucideIcon = icons[name];

    if (!LucideIcon) return null;

    return <LucideIcon size={size} className={className} />;
};

export default Icon;
